services:
  - type: web
    name: vkgym
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CRYPTOCOMPARE_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
